-- Admin Role and MOH Account Creation with OTP
-- This migration adds support for admin role and one-time password creation of MOH accounts

-- Add admin role to the role constraint if it doesn't already exist
-- (This assumes the schema has been updated to include 'admin' in the CHECK constraint)

-- Create a table for MOH account creation OTPs (one-time passwords)
CREATE TABLE IF NOT EXISTS moh_account_otps (
    id              TEXT PRIMARY KEY,
    admin_id        TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    employee_id     TEXT NOT NULL,
    email           TEXT NOT NULL,
    nic             TEXT NOT NULL,
    name            TEXT NOT NULL,
    phone_number    TEXT,
    assigned_area   TEXT NOT NULL,
    otp_hash        TEXT NOT NULL,
    attempt_count   INT NOT NULL DEFAULT 0,
    max_attempts    INT NOT NULL DEFAULT 5,
    consumed_at     TIMESTAMPTZ,
    expires_at      TIMESTAMPTZ NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create index for faster lookups by admin_id and email
CREATE INDEX IF NOT EXISTS idx_moh_account_otps_admin_id ON moh_account_otps(admin_id);
CREATE INDEX IF NOT EXISTS idx_moh_account_otps_email ON moh_account_otps(email);
CREATE INDEX IF NOT EXISTS idx_moh_account_otps_expires_at ON moh_account_otps(expires_at);

-- Add constraint to ensure only one admin user exists
-- This is enforced via application logic, but we can add a check trigger as well
CREATE OR REPLACE FUNCTION check_only_one_admin()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.role = 'admin' THEN
        IF EXISTS (SELECT 1 FROM users WHERE role = 'admin' AND id <> NEW.id) THEN
            RAISE EXCEPTION 'Only one admin user is allowed in the system';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Drop trigger if it exists (to avoid conflicts)
DROP TRIGGER IF EXISTS enforce_single_admin ON users;

-- Create trigger to enforce only one admin
CREATE TRIGGER enforce_single_admin
    BEFORE INSERT OR UPDATE ON users
    FOR EACH ROW
    EXECUTE PROCEDURE check_only_one_admin();

-- Add comment for documentation
COMMENT ON TABLE moh_account_otps IS 'Stores one-time passwords (OTPs) generated by admin for MOH account creation';
COMMENT ON COLUMN moh_account_otps.admin_id IS 'The admin user who generated this OTP';
COMMENT ON COLUMN moh_account_otps.otp_hash IS 'Hash of the OTP code (sent to phone number)';
COMMENT ON COLUMN moh_account_otps.consumed_at IS 'Timestamp when the OTP was used to create a MOH account';

